# Welcome to Jekyll!



title: Welcome to my blog
email: qian_shaojun@163.com
description: I want to to say , I have a dream;
baseurl: "http://www.google.cn"
url: "http://yourdomain.com"
twitter_username: LemoQo
github_username:  LemoQo

# Build settings
markdown: kramdown
