# Site settings
title: LemoQo
url: "Bernou.github.io"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "/bohu-jekyll-theme" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: 热爱编程的c++菜鸟一枚。
# Your information
email: 286361125@qq.com
author: Clark #yourname #LemoQo
place: yourhometown #上海
domain: yourdoamain #互联网
company: yourcompany #保密
position: yourjob #C++服务器
school: yourschool #
major: yourmajoy #测控技术与仪器
resume: "Bernou.github.io"
profile: Time is money. #yourmotto #聪明在于勤奋，天才在于积累。
twitter_username: 
weibo_username:  
github_username:  LemoQo

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: LemoQo   
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
